# Generated by Django 6.0.2 on 2026-04-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0014_tabel_5_1_tatakelola_tabel_5_2_sarana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel_1B_SPMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=255)),
                ('dokumen', models.CharField(max_length=255)),
                ('jml_auditor_cert', models.IntegerField(default=0)),
                ('jml_auditor_non', models.IntegerField(default=0)),
                ('frekuensi_audit', models.IntegerField(default=0)),
                ('link_pt', models.URLField(blank=True, null=True)),
                ('link_upps', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_2C_Fleksibilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bentuk_pembelajaran', models.CharField(max_length=255)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_2D_Rekognisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(max_length=255)),
                ('jenis_pengakuan', models.CharField(max_length=255)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel_3A3_Pengembangan_DTPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pengembangan', models.CharField(max_length=255)),
                ('nama_dosen', models.CharField(max_length=255)),
                ('ts_2', models.IntegerField(default=0)),
                ('ts_1', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
                ('link_bukti', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
