# Generated by Django 6.0.3 on 2026-04-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0015_tabel_1b_spmi_tabel_2c_fleksibilitas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identitaspengusul',
            options={'verbose_name': 'Identitas Pengusul', 'verbose_name_plural': 'Identitas Pengusul'},
        ),
        migrations.AlterModelOptions(
            name='profilpengguna',
            options={'verbose_name': 'Profil Pengguna', 'verbose_name_plural': 'Profil Pengguna'},
        ),
        migrations.AlterModelOptions(
            name='programstudi',
            options={'verbose_name': 'Program Studi', 'verbose_name_plural': 'Program Studi'},
        ),
        migrations.AlterModelOptions(
            name='tabel_1a1',
            options={'verbose_name': '1.A.1 Pimpinan & Tupoksi', 'verbose_name_plural': '1.A.1 Pimpinan & Tupoksi'},
        ),
        migrations.AlterModelOptions(
            name='tabel_1a2_sumber',
            options={'verbose_name': '1.A.2 Sumber Pendanaan', 'verbose_name_plural': '1.A.2 Sumber Pendanaan'},
        ),
        migrations.AlterModelOptions(
            name='tabel_1a3_penggunaan',
            options={'verbose_name': '1.A.3 Penggunaan Dana', 'verbose_name_plural': '1.A.3 Penggunaan Dana'},
        ),
        migrations.AlterModelOptions(
            name='tabel_1a4',
            options={'verbose_name': '1.A.4 Beban Kerja DTPR', 'verbose_name_plural': '1.A.4 Beban Kerja DTPR'},
        ),
        migrations.AlterModelOptions(
            name='tabel_1a5',
            options={'verbose_name': '1.A.5 Tenaga Kependidikan', 'verbose_name_plural': '1.A.5 Tenaga Kependidikan'},
        ),
        migrations.AlterModelOptions(
            name='tabel_1b_spmi',
            options={'verbose_name': '1.B Unit SPMI', 'verbose_name_plural': '1.B Unit SPMI'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2a2_asal',
            options={'verbose_name': '2.A.2 Keragaman Asal', 'verbose_name_plural': '2.A.2 Keragaman Asal'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2a3_kondisi',
            options={'verbose_name': '2.A.3 Kondisi Jumlah', 'verbose_name_plural': '2.A.3 Kondisi Jumlah'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2a_mahasiswa',
            options={'verbose_name': '2.A.1 Data Mahasiswa', 'verbose_name_plural': '2.A.1 Data Mahasiswa'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2b1_mk',
            options={'verbose_name': '2.B.1 Isi Kurikulum', 'verbose_name_plural': '2.B.1 Isi Kurikulum'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2b2_cpl',
            options={'verbose_name': '2.B.2 Pemetaan CPL', 'verbose_name_plural': '2.B.2 Pemetaan CPL'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2b3_pemenuhan',
            options={'verbose_name': '2.B.3 Pemenuhan CPL', 'verbose_name_plural': '2.B.3 Pemenuhan CPL'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2b4_masatunggu',
            options={'verbose_name': '2.B.4 Masa Tunggu', 'verbose_name_plural': '2.B.4 Masa Tunggu'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2b5_bidangkerja',
            options={'verbose_name': '2.B.5 Bidang Kerja', 'verbose_name_plural': '2.B.5 Bidang Kerja'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2b6_kepuasan',
            options={'verbose_name': '2.B.6 Kepuasan Pengguna', 'verbose_name_plural': '2.B.6 Kepuasan Pengguna'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2b_summary',
            options={'verbose_name': '2.B Ringkasan Lulusan', 'verbose_name_plural': '2.B Ringkasan Lulusan'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2c_fleksibilitas',
            options={'verbose_name': '2.C Fleksibilitas Kurikulum', 'verbose_name_plural': '2.C Fleksibilitas Kurikulum'},
        ),
        migrations.AlterModelOptions(
            name='tabel_2d_rekognisi',
            options={'verbose_name': '2.D Rekognisi DTPR', 'verbose_name_plural': '2.D Rekognisi DTPR'},
        ),
        migrations.AlterModelOptions(
            name='tabel_3_summary',
            options={'verbose_name': '3 Ringkasan Penelitian', 'verbose_name_plural': '3 Ringkasan Penelitian'},
        ),
        migrations.AlterModelOptions(
            name='tabel_3a1_sarana',
            options={'verbose_name': '3.A.1 Sarana Penelitian', 'verbose_name_plural': '3.A.1 Sarana Penelitian'},
        ),
        migrations.AlterModelOptions(
            name='tabel_3a2_penelitian',
            options={'verbose_name': '3.A.2 Kegiatan Penelitian', 'verbose_name_plural': '3.A.2 Kegiatan Penelitian'},
        ),
        migrations.AlterModelOptions(
            name='tabel_3a3_pengembangan_dtpr',
            options={'verbose_name': '3.A.3 Pengembangan DTPR', 'verbose_name_plural': '3.A.3 Pengembangan DTPR'},
        ),
        migrations.AlterModelOptions(
            name='tabel_3c1_kerjasama',
            options={'verbose_name': '3.C.1 Kerjasama Penelitian', 'verbose_name_plural': '3.C.1 Kerjasama Penelitian'},
        ),
        migrations.AlterModelOptions(
            name='tabel_3c2_publikasi',
            options={'verbose_name': '3.C.2 Publikasi Ilmiah', 'verbose_name_plural': '3.C.2 Publikasi Ilmiah'},
        ),
        migrations.AlterModelOptions(
            name='tabel_3c3_hki',
            options={'verbose_name': '3.C.3 HKI Penelitian', 'verbose_name_plural': '3.C.3 HKI Penelitian'},
        ),
        migrations.AlterModelOptions(
            name='tabel_4_summary',
            options={'verbose_name': '4 Ringkasan PkM', 'verbose_name_plural': '4 Ringkasan PkM'},
        ),
        migrations.AlterModelOptions(
            name='tabel_4a1_sarana',
            options={'verbose_name': '4.A.1 Sarana PkM', 'verbose_name_plural': '4.A.1 Sarana PkM'},
        ),
        migrations.AlterModelOptions(
            name='tabel_4a2_pkm',
            options={'verbose_name': '4.A.2 Kegiatan PkM', 'verbose_name_plural': '4.A.2 Kegiatan PkM'},
        ),
        migrations.AlterModelOptions(
            name='tabel_4c1_kerjasama',
            options={'verbose_name': '4.C.1 Kerjasama PkM', 'verbose_name_plural': '4.C.1 Kerjasama PkM'},
        ),
        migrations.AlterModelOptions(
            name='tabel_4c2_diseminasi',
            options={'verbose_name': '4.C.2 Diseminasi PkM', 'verbose_name_plural': '4.C.2 Diseminasi PkM'},
        ),
        migrations.AlterModelOptions(
            name='tabel_4c3_hki',
            options={'verbose_name': '4.C.3 HKI PkM', 'verbose_name_plural': '4.C.3 HKI PkM'},
        ),
        migrations.AlterModelOptions(
            name='tabel_5_1_tatakelola',
            options={'verbose_name': '5.1 Tata Kelola & SI', 'verbose_name_plural': '5.1 Tata Kelola & SI'},
        ),
        migrations.AlterModelOptions(
            name='tabel_5_2_sarana',
            options={'verbose_name': '5.2 Sarana Pendidikan', 'verbose_name_plural': '5.2 Sarana Pendidikan'},
        ),
        migrations.AlterModelOptions(
            name='tabel_6_misi',
            options={'verbose_name': '6 Visi & Misi', 'verbose_name_plural': '6 Visi & Misi'},
        ),
        migrations.AlterModelOptions(
            name='timpenyusun',
            options={'verbose_name': 'Tim Penyusun', 'verbose_name_plural': 'Tim Penyusun'},
        ),
    ]
