# Generated by Django 6.0.3 on 2026-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0016_alter_identitaspengusul_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabel_1a4',
            name='sks_tambahan',
        ),
        migrations.AddField(
            model_name='tabel_1a4',
            name='sks_manajemen_pt_lain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tabel_1a4',
            name='sks_manajemen_pt_sendiri',
            field=models.FloatField(default=0),
        ),
    ]
